don't rely on DEBHELPER macro, include the scripts.

diff --git a/debian/argus-pdp.postinst b/debian/argus-pdp.postinst
--- a/debian/argus-pdp.postinst
+++ b/debian/argus-pdp.postinst
@@ -24,7 +24,7 @@ case "$1" in
     #TODO: for jarname in argus-pdp-pep-common voms-api-java trustmanager ; do
     for jarname in argus-pdp-pep-common ; do
         if [ ! -f /usr/share/java/$jarname.jar ] ; then
-           echo "postinst: missing dependency jar file: $jarname.jar" >&2
+           echo "$0: missing dependency jar file: $jarname.jar" >&2
            exit 1
         fi
         ln -fs /usr/share/java/$jarname.jar /var/lib/argus/pdp/lib
@@ -40,8 +40,19 @@ case "$1" in
     ;;
 esac
 
-# dh_installdeb will automatically replace this a "register service" and "start service" script
+# register the service
+if [ -x "/etc/init.d/argus-pdp" ]; then
+    update-rc.d argus-pdp defaults >/dev/null
+fi
 
-#DEBHELPER#
-
+# start the service on upgrade, install(config-files), downgrade
+# in these cases postinst is called 'postinst configure <version>', and we check
+# if <version> exists
+if [ -n "$2" ]; then
+    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+        invoke-rc.d argus-pdp start || exit $?
+    else
+        /etc/init.d/argus-pdp start || exit $?
+    fi
+fi
 exit 0
