new PDP_USE_OS_comp vars and logic.

diff --git a/src/main/scripts/sbin/pdpctl b/src/main/scripts/sbin/pdpctl
--- a/src/main/scripts/sbin/pdpctl
+++ b/src/main/scripts/sbin/pdpctl
@@ -55,9 +55,32 @@ if [ ! -x "$JAVACMD" ] ; then
     exit 1
 fi
 
-# uses pdp-pep-common, voms-api-java, trustmanager and bouncycastle from
-# the install RPM packages (see .postinstall script and build-jar-repository)
-LOCALCLASSPATH=""
+# uses pdp-pep-common, canl and bouncycastle from
+# the install RPM packages
+LOCALCLASSPATH="/usr/share/java/argus-pdp-pep-common.jar"
+if [ "$PDP_USE_OS_CANL" = "false" ] ; then
+	for jar in $PDP_LIBDIR/provided/canl-*.jar
+	do
+	    if [ -f "$jar" ] ; then
+	        LOCALCLASSPATH="$LOCALCLASSPATH:$jar"
+	    fi
+	done
+else
+    LOCALCLASSPATH="$LOCALCLASSPATH:/usr/share/java/canl.jar"
+fi
+if [ "$PDP_USE_OS_BCPROV" = "false" ] ; then
+	for jar in $PDP_LIBDIR/provided/bcprov-*.jar
+	do
+	    if [ -f "$jar" ] ; then
+	        LOCALCLASSPATH="$LOCALCLASSPATH:$jar"
+	    fi
+	done
+else
+    LOCALCLASSPATH="$LOCALCLASSPATH:/usr/share/java/bcprov-1.46.jar"
+fi
+
+
+# include all embedded jar
 jarfiles="$PDP_LIBDIR/*.jar"
 for jar in $jarfiles
 do
@@ -73,6 +96,17 @@ if [ -z "$LOCALCLASSPATH" ]; then
     echo "$0: ERROR: LOCALCLASSPATH empty, check the $PDP_LIBDIR directory"
     exit 1
 fi
+
+# check that all jars in classpath exist
+check_jarfiles="$(echo $LOCALCLASSPATH | sed 's/:/ /g')"
+for jar in $check_jarfiles
+do
+    if [ ! -f "$jar" ] ; then
+    	echo "$0: ERROR: $jar in classpath does not exist"
+    	exit 1
+    fi	
+done
+
 # check endorsed directory
 if [ ! -d "$PDP_ENDORSEDDIR" ]; then
     echo "$0: ERROR: $PDP_ENDORSEDDIR does not exist"
