don't bundle pdp-pep-common anymore. use the RPM package from /usr/share/java.

diff --git a/src/main/scripts/sbin/pdpctl b/src/main/scripts/sbin/pdpctl
--- a/src/main/scripts/sbin/pdpctl
+++ b/src/main/scripts/sbin/pdpctl
@@ -52,7 +52,14 @@ if [ ! -f "$USR_SHARE_JAVA/trustmanager.jar" ] ; then
 fi
 LOCALCLASSPATH="$USR_SHARE_JAVA/vomsjapi.jar:$USR_SHARE_JAVA/trustmanager.jar"
 
-# add in the dependency .jar files from the lib directory
+# add argus-pdp-pep-common from /usr/share/java in classpath
+if [ ! -f "$USR_SHARE_JAVA/argus-pdp-pep-common.jar" ] ; then
+    echo "$0: ERROR: $USR_SHARE_JAVA/argus-pdp-pep-common.jar not found, Argus PDP/PEP common package not installed"
+    exit 1
+fi
+LOCALCLASSPATH="$USR_SHARE_JAVA/argus-pdp-pep-common.jar:$LOCALCLASSPATH"
+
+# add the other bundled .jar files from the pepd lib directory
 jarfiles="$PDP_LIBDIR/*.jar"
 for jar in $jarfiles
 do
