Bug fix for 'service argus-pepd status' as user. See https://ggus.eu/?mode=ticket_info&ticket_id=100322

diff --git a/src/main/scripts/init.d/argus-pdp b/src/main/scripts/init.d/argus-pdp
--- a/src/main/scripts/init.d/argus-pdp
+++ b/src/main/scripts/init.d/argus-pdp
@@ -34,19 +34,14 @@
 # Author(s): Joel Casutt <argus-support@cern.ch>
 #            Valery Tschopp <argus-support@cern.ch>
 #
-# Version: V2.4
-# Date: 28/09/2012
+# Version: V2.5
+# Date: 2014-04-08
 ###############################################################################
 # set -x
 
 # PDP server control script and name of the script
 PDPCTL="/usr/sbin/pdpctl"
 NAME="argus-pdp"
-
-if [ `id -u` -ne 0 ]; then
-    echo "You need root privileges to run this script"
-    exit 1
-fi 
 
 # Source functions Library
 if [ -r "/lib/lsb/init-functions" ]; then
@@ -85,9 +80,16 @@ elif [ -r "/etc/default/$NAME" ]; then
     source "/etc/default/$NAME"
 fi
 
+function _check_root_user() {
+    if [ `id -u` -ne 0 ]; then
+        echo "ERROR: You need root privileges to run this command"
+        exit 1
+    fi 
+}
 
 # Function to start the PDP daemon
 function start() {
+    _check_root_user
     echo -n "Starting $PDP_PROG... "
     # get the current state of the program, this also creates appropriate pid and lock files
     # if the program is running but the files are missing.
@@ -119,6 +121,7 @@ function start() {
 
 # Function to stop the PDP
 function stop() {
+    _check_root_user
     echo -n "Stopping $PDP_PROG... "
     _current_state
     state=$?
@@ -163,11 +166,12 @@ function status() {
 
 # Function to read the info of the PDP
 function info() {
+    _check_root_user
     _current_state
     state=$?
     if [ $state -eq 5 ]; then
         echo "$PDP_PROG is not running..."
-        return $state
+        return 1
     else
         $PDPCTL status
     fi
@@ -175,6 +179,7 @@ function info() {
 
 # Function to reload the policies from the pap
 function reloadpolicy() {
+    _check_root_user
     _current_state
     state=$?
     if [ $state -eq 5 ]; then
@@ -187,7 +192,8 @@ function reloadpolicy() {
 
 # Function to read the version of the PDP
 function version() {
-     _current_state
+    _check_root_user
+    _current_state
     $PDPCTL version
 }
 
